# Generated by Django 5.0.6 on 2024-05-31 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_currency", models.CharField(max_length=3)),
                (
                    "from_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="From Amount"
                    ),
                ),
                ("to_currency", models.CharField(max_length=3)),
                (
                    "to_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="To Amount"
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Rate"
                    ),
                ),
                ("created_at", models.DateTimeField(verbose_name="Created At")),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversion",
                "verbose_name_plural": "Conversions",
            },
        ),
    ]
