# Generated by Django 5.0.6 on 2024-06-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversion", "0002_rename_user_id_conversion_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversion",
            name="rates_timestamp",
            field=models.DateTimeField(verbose_name="Rates Timestamp"),
        ),
    ]
