# Generated by Django 5.0.6 on 2024-06-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversion", "0003_alter_conversion_rates_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversion",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Created At"
            ),
        ),
    ]
