# Generated by Django 5.0.6 on 2024-06-02 19:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversion", "0004_conversion_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversion",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Created At",
            ),
            preserve_default=False,
        ),
    ]
