name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Add Poetry to PATH
        run: echo "${{ runner.tool_cache }}/python/$(ls ${{ runner.tool_cache }}/python)/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: poetry install

      - name: Run migrations
        run: |
          poetry run python manage.py migrate

      - name: Run tests
        run: |
          poetry run python manage.py test

      - name: Run Ruff
        run: poetry run ruff check .

      - name: Run mypy
        run: poetry run mypy .
