name: Testing

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      EXCHANGE_API_KEY: ${{ secrets.EXCHANGE_API_KEY }}

    steps:
      - uses: ./.github/actions/setup-python-poetry

      - name: Install dependencies
        run: poetry install

      - name: Run migrations
        run: |
          cd currency_converter
          poetry run python manage.py migrate

      - name: Run tests
        run: |
          cd currency_converter
          poetry run python manage.py test
